name: movie_app_flutter
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  go_router: 14.2.3
  flutter_riverpod: 2.5.1
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  talker_flutter: 4.4.1
  talker_riverpod_logger: 4.4.1
  talker_dio_logger: 4.4.1
  dio: 5.6.0
  openapi:
    path: ./api

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint:
  flutter_lints: 4.0.0
  build_runner: 2.4.12
  freezed: 2.5.7
  json_serializable: 6.8.0
  riverpod_lint: 2.3.13

flutter:
  uses-material-design: true